import { motion } from 'framer-motion'
import { useState } from 'react'
import { useStore } from '../store/useStore'
import { Icon, PrimaryPill, SectionTitle, Segmented, Reveal } from './ui'
import { fmtTime, HOUR, MIN } from '../lib/time'
import { useTicker } from '../hooks/useTicker'

const kindMeta: Record<string, { color: string; icon: string }> = {
  task: { color: '#8b5cf6', icon: 'bolt' },
  break: { color: '#22d3ee', icon: 'coffee' },
  buffer: { color: '#64748b', icon: 'hourglass_empty' },
}

type ViewMode = 'timeline' | 'calendar'

export default function Planner() {
  const tick = useTicker()
  const { plan, replan, thinking, tasks } = useStore()
  const [view, setView] = useState<ViewMode>('timeline')

  const hasBlocks = plan && plan.blocks.length > 0

  return (
    <div className="mx-auto w-full max-w-3xl">
      <div className="mb-4 flex flex-wrap items-center justify-between gap-3">
        <SectionTitle icon="calendar_view_day" sub="Hour-by-hour rescue plan with micro-steps">
          Day planner
        </SectionTitle>
        <div className="flex items-center gap-2">
          <Segmented<ViewMode>
            value={view}
            onChange={setView}
            options={[
              { value: 'timeline', label: 'Timeline', icon: 'view_timeline' },
              { value: 'calendar', label: 'Calendar', icon: 'calendar_month' },
            ]}
          />
          <PrimaryPill icon="auto_awesome" onClick={() => replan()} disabled={thinking}>
            {thinking ? 'Planning…' : 'Re-plan'}
          </PrimaryPill>
        </div>
      </div>

      {plan && (
        <div className="glass mb-5 flex items-start gap-3 rounded-2xl p-4">
          <Icon name="tips_and_updates" className="mt-0.5 text-[22px] text-neon-violet" />
          <div>
            <p className="text-sm leading-relaxed text-white/80">{plan.summary}</p>
            <span className="mt-1 inline-flex items-center gap-1 text-[11px] text-white/40">
              <Icon name={plan.source === 'gemini' ? 'auto_awesome' : 'memory'} className="text-[13px]" />
              {plan.source === 'gemini' ? 'Generated by Gemini' : 'Local reasoning engine'}
            </span>
          </div>
        </div>
      )}

      {!hasBlocks ? (
        <div className="glass rounded-3xl p-12 text-center">
          <Icon name="event_busy" className="text-[44px] text-white/30" />
          <p className="mt-3 text-sm text-white/50">
            {tasks.filter((t) => !t.done).length === 0
              ? 'Add a task and the agent will build your timeline.'
              : 'Tap Re-plan to generate your schedule.'}
          </p>
        </div>
      ) : view === 'timeline' ? (
        <TimelineView blocks={plan!.blocks} tick={tick} />
      ) : (
        <CalendarView blocks={plan!.blocks} tick={tick} />
      )}
    </div>
  )
}

function TimelineView({ blocks, tick }: { blocks: any[]; tick: number }) {
  return (
    <div className="relative pl-6">
      <div className="absolute left-[7px] top-2 bottom-2 w-0.5 bg-gradient-to-b from-neon-blue via-neon-violet to-neon-magenta" />
      {blocks.map((b: any, i: number) => {
        const meta = kindMeta[b.kind]
        const active = tick >= b.start && tick < b.end
        return (
          <motion.div
            key={b.id}
            initial={{ opacity: 0, x: 30, rotateY: -15 }}
            whileInView={{ opacity: 1, x: 0, rotateY: 0 }}
            viewport={{ once: true, amount: 0.3 }}
            transition={{ delay: i * 0.04, type: 'spring', stiffness: 200, damping: 22 }}
            className="relative mb-3"
            style={{ perspective: 1000 }}
          >
            <span
              className="absolute -left-[22px] top-4 grid h-4 w-4 place-items-center rounded-full ring-4 ring-ink"
              style={{ background: meta.color }}
            />
            <div
              className={`glass rounded-2xl p-4 ${active ? 'ring-1 ring-neon-violet/60 shadow-glow' : ''}`}
              style={{ transformStyle: 'preserve-3d' }}
            >
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <span className="grid h-7 w-7 place-items-center rounded-lg" style={{ background: `${meta.color}22`, color: meta.color }}>
                    <Icon name={meta.icon} className="text-[16px]" />
                  </span>
                  <span className="font-display font-semibold text-white">{b.title}</span>
                </div>
                <span className="text-xs tabular-nums text-white/50">
                  {fmtTime(b.start)} – {fmtTime(b.end)}
                </span>
              </div>
              {active && (
                <span className="mt-1 inline-flex items-center gap-1 text-[11px] font-semibold text-neon-pink">
                  <span className="h-1.5 w-1.5 animate-ping rounded-full bg-neon-pink" /> Happening now
                </span>
              )}
              {b.microSteps.length > 0 && (
                <ul className="mt-2 space-y-1">
                  {b.microSteps.map((s: string, j: number) => (
                    <li key={j} className="flex items-center gap-2 text-xs text-white/65">
                      <Icon name="chevron_right" className="text-[14px] text-white/30" />
                      {s}
                    </li>
                  ))}
                </ul>
              )}
            </div>
          </motion.div>
        )
      })}
    </div>
  )
}

/** Google Calendar-style day grid: hour rows with blocks positioned by time. */
function CalendarView({ blocks, tick }: { blocks: any[]; tick: number }) {
  const PX_PER_MIN = 1.2
  const starts = blocks.map((b) => b.start)
  const ends = blocks.map((b) => b.end)
  const gridStart = Math.floor(Math.min(...starts, tick) / HOUR) * HOUR
  const gridEnd = Math.ceil(Math.max(...ends, tick + HOUR) / HOUR) * HOUR
  const hours: number[] = []
  for (let t = gridStart; t <= gridEnd; t += HOUR) hours.push(t)
  const totalMin = (gridEnd - gridStart) / MIN
  const height = totalMin * PX_PER_MIN
  const nowTop = ((tick - gridStart) / MIN) * PX_PER_MIN

  return (
    <Reveal className="glass rounded-3xl p-4">
      <div className="relative" style={{ height }}>
        {/* hour rows */}
        {hours.map((h) => {
          const top = ((h - gridStart) / MIN) * PX_PER_MIN
          return (
            <div key={h} className="absolute inset-x-0 flex items-start gap-2" style={{ top }}>
              <span className="w-12 shrink-0 -translate-y-2 text-right text-[10px] tabular-nums text-white/35">
                {fmtTime(h)}
              </span>
              <div className="h-px flex-1 translate-y-[1px] bg-white/8" />
            </div>
          )
        })}

        {/* now line */}
        {nowTop >= 0 && nowTop <= height && (
          <div className="absolute inset-x-0 z-20 flex items-center gap-1" style={{ top: nowTop, left: 56 }}>
            <span className="h-2 w-2 rounded-full bg-neon-pink shadow-glow" />
            <div className="h-px flex-1 bg-neon-pink/70" />
          </div>
        )}

        {/* blocks */}
        <div className="absolute inset-y-0" style={{ left: 56, right: 4 }}>
          {blocks.map((b, i) => {
            const meta = kindMeta[b.kind]
            const top = ((b.start - gridStart) / MIN) * PX_PER_MIN
            const h = Math.max(22, ((b.end - b.start) / MIN) * PX_PER_MIN - 4)
            const active = tick >= b.start && tick < b.end
            return (
              <motion.div
                key={b.id}
                initial={{ opacity: 0, x: 20, rotateY: -12 }}
                whileInView={{ opacity: 1, x: 0, rotateY: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.04, type: 'spring', stiffness: 220, damping: 22 }}
                className="absolute left-0 right-0 overflow-hidden rounded-xl border p-2"
                style={{
                  top,
                  height: h,
                  background: `${meta.color}1f`,
                  borderColor: `${meta.color}55`,
                  boxShadow: active ? `0 0 22px ${meta.color}66` : undefined,
                }}
              >
                <div className="flex items-center gap-1.5">
                  <Icon name={meta.icon} className="text-[14px]" />
                  <span className="truncate text-xs font-semibold text-white">{b.title}</span>
                </div>
                {h > 38 && (
                  <span className="text-[10px] tabular-nums text-white/55">
                    {fmtTime(b.start)} – {fmtTime(b.end)}
                  </span>
                )}
              </motion.div>
            )
          })}
        </div>
      </div>
    </Reveal>
  )
}
